### ISSUE TITLE
First Milestone Tasks

### ISSUE THREAD

**Issue by ryyppy** [reason-association/bs-platform-js#1]
- [ ] extract the `repl.js` / `playground` and other related files from bucklescript to this repo
- [x] Set up a github action to clone and build BuckleScript master with the vendored jsoo bytecode(#2)
- [x] Use the github action for nightly builds

**Comment by ryyppy** [comment]
not sure if point 1 actually makes sense... repl.js is kinda coupled to the bs repo anyways

**Comment by jchavarri** [comment]
yes, I think it makes sense to leave it there, as the `jsoo_main.ml` sources are staying as well.

**Comment by ryyppy** [comment]
i think this is done now, thanks @jchavarri  🎉
